name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Allow Actions to push to the repository

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Replace with your required Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure this token is available
